### ISSUE TITLE
Started to occupy Port 80 after a reboot of UnRaid

### ISSUE THREAD

**Issue by usafle** [demonrik/HDHR-DVR-docker#2]
Iv'e been running this docker container for a while now and it survived multiple reboots of my UnRaid system without issue.  
Just during a recent reboot however, the docker is now occupying Port80.  Which, as you can imagine, made accessing UnRaids WebGUI impossible.

I am not sure how to now stop this docker from occupying Port80. https://i.imgur.com/o4XMLaZ.png

**Comment by demonrik** [comment]
yeah - unforeseen issue.
With the addition of the GUI - I should have allowed to shift that port.
Can you try using a bridged network and map the 59090 port to host 59090 and 80 to a free port on the host?

EDIT - I am fixing the port to be configurable in future release.. got stuck behind another issue

**Comment by usafle** [comment]
Ok.  I will wait patiently for you to fix the issue in a future release.  Because I have _just enough knowledge to be dangerous to myself._

It's taken me weeks trying to figure out what happened and how to get back into my UnRaid GUI.  I will just leave it disabled until you push the update.  If I start messing around with bridging networks and such, my head and quite possibly my tower will explode. lol

**Comment by demonrik** [comment]
Update just pushed
You can change the NGINX/UI port by setting the DVRUI_PORT variable to a free port on your system. Obviously check firewalls, etc.

**Comment by usafle** [comment]
So I just pulled down your update (thank you for that) but there is no DVRUI_PORT in the 'config' of the docker. The only line entry in the config is the same as it was before: **Container Path: /dvrdata**

**Comment by usafle** [comment]
I can't access the new GUI either.

 I've tried to add a "variable" to the config with DVRUI_PORT and a free port - doesn't work. 
 I tried to add a new port with a DVRUI_PORT and  still nothing.

Either community apps doesn't have your updated docker yet, and it pulled something else down or, it just simply isn't working.

**Comment by demonrik** [comment]
I don't know how community apps pulls it down - I suspect they just pull it from dockerhub without any knowledge.
The update is there today to be applied.
As to seeing the variable - I certainly haven't submited a template for it, which is what would really be needed for an Unraid integration.
So, you won't see an entry for the DVRUI_PORT until someone updates the template that was created (no idea who created).

To add you will need to edit the container, and select 'Add another Path, Port, Variable, Label or Device'
Set Config Type to 'Variable'
Give this a name - e.g. 'DVRUI_PORT'
set Key to 'DVRUI_PORT'
set Value to the port number you want to use.
Save
Then select Done for the container.

Tip - while in there editing, click on the toggle button at the top to shift into advanced mode and add the IP/Port to the WebUI field so that you can open direct to the UI when needed.

**Comment by usafle** [comment]
Thanks for the detailed reply.  It pulled down another update today but again, your config/DVRUI port did not populate.  I can't be the only UnRaid user our there that is using your docker - I would hope.  Looking at the config for the docker container it's pulling it down right from your repo: _demonrik/hdhrdvr-docker_  I don't think anyone created any template.  Yours just shows up when searching for HDHOMERUN in the Community Apps store.

If I knew how to submit a template for it for you to Community Apps, I would.  I wouldn't want anyone else having to go through this and get yelled at by their Significant Other as to "WHY ARE MY SHOWS NOT BEING RECORDED???" lol

I followed your instructions and was able to access the new DVR GUI.

Again, thanks.  If it wasn't for you, I wouldn't be able to use this on my NAS.

**Comment by demonrik** [comment]
I'll do a template once I have the UID/GID mapping working, then I'll have all the variables I need, so makes it simpler
